config:
  plugins:
    metrics-by-endpoint: {}
  target: 'http://localhost:3000'
  phases:
    - duration: 20
      arrivalRate: 5
      name: "Prueba rendimiento Login / Registro"
scenarios:
  - name: "Sessions Flow (registro + login)"
    flow:
      - log: "Creamos las variables para el usuario de prueba"
      - get:
          url: "/generate-data-user"
          capture:
            - json: "$.usuario.nombre"
              as: "nombre"
            - json: "$.usuario.apellido"
              as: "apellido"
            - json: "$.usuario.email"
              as: "email"
            - json: "$.usuario.password"
              as: "password"
      - log: "Registro de usuario {{nombre}} {{apellido}}"
      - post:
          url: "/api/sessions/registro"
          json:
            nombre: "{{nombre}}"
            apellido: "{{apellido}}"
            email: "{{email}}"
            password: "{{password}}"
      - think: 2
      - log: "Login usuario {{email}}"
      - post:
          url: "/api/sessions/login"
          json:
            email: "{{email}}"
            password: "{{password}}"


# ```bash
# config:
#   plugins:
#     metrics-by-endpoint: {}
#   target: 'http://localhost:3000'
#   phases:
#     - duration: 20     <--- es el tiempo en que se ejecutan las pruebas con el FLOW
#       arrivalRate: 5   <--- 5 peticiones por segundo
#       el total es 100 veces cada FLOW
# Nuestro FLOW de ejemplo ejecuta 3 peticiones -> el número final de peticiones 
# según nuestro config.yml es de 300 peticiones
# ```